AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  Policy: 
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      Description: 3CS AutoMirror from Serverless App Repository
      Path: /
      ManagedPolicyName: 3CS-AutoMirror
      PolicyDocument: 
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
            - ec2:DescribeInstances
            - ec2:DescribeTrafficMirrorFilters
            - ec2:DescribeTrafficMirrorTargets
            - ec2:CreateTags
            - ec2:CreateTrafficMirrorSession
            - ec2:DescribeTrafficMirrorSessions
            - ec2:createTrafficMirrorFilterRule
            - ec2:createTrafficMirrorFilter
            Resource: '*'
          - Effect: Allow
            Action:
            - logs:*
            Resource: "arn:aws:logs:*:*:*"
  Role:
    Type: AWS::IAM::Role
    Properties:
      Description: 3CS Automirror from Serverless App Repository
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns: 
        - !Ref Policy
      RoleName: 3CS-AutoMirror
  Function:
    Type: AWS::Serverless::Function
    Properties: 
      Role: !GetAtt Role.Arn
      Description: 3CS AutoMirror from Serverless App Repository
      CodeUri: s3://3cs-serverless-apps/automirror/automirror.zip
      Handler: index.handler
      Runtime: nodejs10.x
      FunctionName: 3CS-AutoMirror
      Timeout: 30
      ReservedConcurrentExecutions: 1
  EventRule: 
    Type: AWS::Events::Rule
    Properties: 
      Name: 3CS-AutoMirror-Trigger
      Description: 3CS AutoMirror from Serverless App Repository
      EventPattern: 
        source: 
          - "aws.ec2"
        detail-type: 
          - "EC2 Instance State-change Notification"
        detail: 
          state: 
            - "pending"
      State: "ENABLED"
      Targets: 
        - Arn: !GetAtt Function.Arn
          Id: "3CS-AutoMirror"
  PermissionForEventsToInvokeLambda: 
    Type: AWS::Lambda::Permission
    Properties: 
      FunctionName: 3CS-AutoMirror
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: 
        Fn::GetAtt: 
          - "EventRule"
          - "Arn"
